### ISSUE TITLE
ioff for linear index appears to be set improperly for empty bins

### ISSUE THREAD

**Issue by carsonhh** [samtools/htslib#486]
When an interval of the linear index is empty (no overlapping features), it is being set to the ioff of the previous upstream interval. This means the feature found at that location does not overlap the desired bin and instead can be found far upstream of that bin. I believe the more logical behavior would be to instead set ioff of the empty interval to that of the next downstream interval with a valid ioff. The downstream ioff would correspond to the location of where the first overlapping feature could occur if it existed.

Without the proper setting, chunks in the bin index appear as if they could belong to the empty location because ioff occurs too far upstream so more cnk_end locations artificially pass the linear index filter. If ioff is instead set to the next valid downstream ioff as mentioned, then these chunks can be properly ignored. Being able to assign chunks accurately is important for example when estimating bin content using the index as a proxy for coverage (i.e. estimating attributes of a dataset without having to parse it).

**Comment by carsonhh** [comment]
Note the function doing this is --> update_loff in hts.c

Here -->
   for (; l < lidx->n; ++l) // fill missing values
        if (lidx->offset[l] == (uint64_t)-1)
            lidx->offset[l] = lidx->offset[l-1];

It should work back to front as opposed to front to back.

**Comment by pd3** [comment]
I believe this might have been fixed by this recent commit https://github.com/samtools/htslib/commit/5c695a174f74f5785bb5a6b27713d234147dbdb8. Can you please try if this solves the problem? If not, a test case would be helpful.

**Comment by carsonhh** [comment]
Getting back to this after a long long time. No. That is not the same issue and does not fix this. The issue still exists in the current master branch. The solution was already given in my previous comment. You should not be using the prior bin to fill in an empty bin, rather you use the next bin over, i.e. you have fill in back to front (reverse the for loop)

Something like this

l = lidx->n -1;
for (; l >= 0; --l) // fill missing values
if (lidx->offset[l] == (uint64_t)-1)
lidx->offset[l] = lidx->offset[l+1];

**Comment by valeriuo** [comment]
> The issue still exists in the current master branch.

Can you describe the issue better? A concrete test case that exposes the problem would be much appreciated.

Arguably, setting an empty linear index entry to its left neighbour value (upstream, to use your terminology) is a conservative choice, which might lead to a small performance penalty, although the iterators have some checks for coordinate boundaries.

**Comment by valeriuo** [comment]
Fixed by https://github.com/samtools/htslib/pull/1286
