### ISSUE TITLE
plugins based on hfile_libcurl appear to be not threadsafe

### ISSUE THREAD

**Issue by dalexander** [samtools/htslib#597]
I have been trying to access FASTA and BAM files on Google Cloud Storage using the hfile_gcs plugin (which is a thin wrapper around the hfile_libcurl library).  Further, I've been trying to launch multiple reader threads (all of which separately allocate their handles---I am *not* trying to share any handles).

My program crashes reliably as soon as I use more than one thread.

Inspection of the hfile_libcurl library shows that it uses the `curl_multi_*` APIs without any external synchronization, and using a single statically allocated "CURLM" handle .  These `curl_multi_*` APIs do not appear to be intrinsically threadsafe---they seem to be intended for single-threaded event-loop style programming.   Consult: https://github.com/curl/curl/blob/master/lib/multi.c; example problematic usage example here: https://github.com/samtools/htslib/blob/57e2fbe9f9afbd8555e1838dc5ccf281403f494d/hfile_libcurl.c#L547 --- no locking around adding this handle to the "multi" pool.

I think if we switched to using the `curl_easy_*` APIs, we would get thread safety.  What do you think?

Happy to provide the crashing test case if it helps.

**Comment by daviesrob** [comment]
This should have been fixed by 887952e6, which removed the static `CURLM` handle.  In fact, in the line you quote above `fp->multi` is part of `hfile_libcurl *fp`.  We have to use the multi interface as we want to be able to pause connections until the reader asks for more data.  Giving each hfile its own `CURLM`  solved the concurrency problem without having to put locks all over the place (as long as the hfile is only accessed by one thread at a time).  There is a shared `CURLSH` handle, but that is protected by a mutex.

If you've managed to get an up to date `develop` branch to crash, then I'd like to see a test case as it's not supposed to happen.

**Comment by dalexander** [comment]
Oh that's great.  I'll try the develop branch.

**Comment by dkj** [comment]
@dalexander this fix should be in the 1.6 release - please reopen if not fixed....
